language: cpp

matrix:
    include:
        - os: linux
          env: DFLAG="-DUSEOMP" OPTFLAG="-msse"
        - os: linux
          env: DFLAG="-DUSEOMP" OPTFLAG="-mavx"
        - os: linux
          env: DFLAG="-DUSEOMP" OPTFLAG="-DNOSSE"
        - os: linux
          env: DFLAG="-Wl,--no-as-needed"
        - os: osx
          env: DFLAG="" OMPFLAG=""

install:
    - make -e all
    - make -e lib

script:
    - cd demo && sh demo.sh
