name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: make
      # - run: cd demo && sh demo.sh

      - run: sed -i "s/\$train/valgrind --leak-check=yes \$train/g" demo/demo.sh
      - run: sed -i "s/\$predict/valgrind --leak-check=yes \$predict/g" demo/demo.sh
      - run: sudo apt-get update && sudo apt-get install valgrind
      - run: cd demo && sh demo.sh
